apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arrienda-front
  namespace: front
spec:
  ingressClassName: public
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: arrienda-front
            port:
              number: 80
